spring.application.name=ambulance-os

# DATABASE
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ambulance_os}
spring.datasource.username=${DB_USERNAME:aayushverma}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# SERVER
server.port=${PORT:8080}

# GRAPH
ambulance.graph.path=${AMBULANCE_GRAPH_PATH:data/osm/gurgaon_graph.json}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}